# Altana Atlas API
#
# Altana Atlas for Regulatory Risk and Trade Compliance
#
# OpenAPI spec version: {{ version or \"v0.0.1\" }}
# Contact: engineering@altanatech.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' BaseEdge Class
#'
#' @field edge_type 
#' @field edge_canon_id 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BaseEdge <- R6::R6Class(
  'BaseEdge',
  public = list(
    `edge_type` = NULL,
    `edge_canon_id` = NULL,
    initialize = function(`edge_type`, `edge_canon_id`){
      if (!missing(`edge_type`)) {
        stopifnot(is.character(`edge_type`), length(`edge_type`) == 1)
        self$`edge_type` <- `edge_type`
      }
      if (!missing(`edge_canon_id`)) {
        stopifnot(is.character(`edge_canon_id`), length(`edge_canon_id`) == 1)
        self$`edge_canon_id` <- `edge_canon_id`
      }
    },
    toJSON = function() {
      BaseEdgeObject <- list()
      if (!is.null(self$`edge_type`)) {
        BaseEdgeObject[['edge_type']] <- self$`edge_type`
      }
      if (!is.null(self$`edge_canon_id`)) {
        BaseEdgeObject[['edge_canon_id']] <- self$`edge_canon_id`
      }

      BaseEdgeObject
    },
    fromJSON = function(BaseEdgeJson) {
      BaseEdgeObject <- jsonlite::fromJSON(BaseEdgeJson)
      if (!is.null(BaseEdgeObject$`edge_type`)) {
        self$`edge_type` <- BaseEdgeObject$`edge_type`
      }
      if (!is.null(BaseEdgeObject$`edge_canon_id`)) {
        self$`edge_canon_id` <- BaseEdgeObject$`edge_canon_id`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "edge_type": %s,
           "edge_canon_id": %s
        }',
        self$`edge_type`,
        self$`edge_canon_id`
      )
    },
    fromJSONString = function(BaseEdgeJson) {
      BaseEdgeObject <- jsonlite::fromJSON(BaseEdgeJson)
      self$`edge_type` <- BaseEdgeObject$`edge_type`
      self$`edge_canon_id` <- BaseEdgeObject$`edge_canon_id`
    }
  )
)
