# Altana Atlas API
#
# Altana Atlas for Regulatory Risk and Trade Compliance
#
# OpenAPI spec version: {{ version or \"v0.0.1\" }}
# Contact: engineering@altanatech.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' Company Class
#'
#' @field company_name 
#' @field altana_canon_id 
#' @field restrictions 
#' @field risks 
#' @field company_context 
#' @field data_sources 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Company <- R6::R6Class(
  'Company',
  public = list(
    `company_name` = NULL,
    `altana_canon_id` = NULL,
    `restrictions` = NULL,
    `risks` = NULL,
    `company_context` = NULL,
    `data_sources` = NULL,
    initialize = function(`company_name`, `altana_canon_id`, `restrictions`, `risks`, `company_context`, `data_sources`){
      if (!missing(`company_name`)) {
        stopifnot(is.character(`company_name`), length(`company_name`) == 1)
        self$`company_name` <- `company_name`
      }
      if (!missing(`altana_canon_id`)) {
        stopifnot(is.character(`altana_canon_id`), length(`altana_canon_id`) == 1)
        self$`altana_canon_id` <- `altana_canon_id`
      }
      if (!missing(`restrictions`)) {
        stopifnot(is.list(`restrictions`), length(`restrictions`) != 0)
        lapply(`restrictions`, function(x) stopifnot(R6::is.R6(x)))
        self$`restrictions` <- `restrictions`
      }
      if (!missing(`risks`)) {
        stopifnot(is.list(`risks`), length(`risks`) != 0)
        lapply(`risks`, function(x) stopifnot(R6::is.R6(x)))
        self$`risks` <- `risks`
      }
      if (!missing(`company_context`)) {
        stopifnot(R6::is.R6(`company_context`))
        self$`company_context` <- `company_context`
      }
      if (!missing(`data_sources`)) {
        stopifnot(is.list(`data_sources`), length(`data_sources`) != 0)
        lapply(`data_sources`, function(x) stopifnot(is.character(x)))
        self$`data_sources` <- `data_sources`
      }
    },
    toJSON = function() {
      CompanyObject <- list()
      if (!is.null(self$`company_name`)) {
        CompanyObject[['company_name']] <- self$`company_name`
      }
      if (!is.null(self$`altana_canon_id`)) {
        CompanyObject[['altana_canon_id']] <- self$`altana_canon_id`
      }
      if (!is.null(self$`restrictions`)) {
        CompanyObject[['restrictions']] <- lapply(self$`restrictions`, function(x) x$toJSON())
      }
      if (!is.null(self$`risks`)) {
        CompanyObject[['risks']] <- lapply(self$`risks`, function(x) x$toJSON())
      }
      if (!is.null(self$`company_context`)) {
        CompanyObject[['company_context']] <- self$`company_context`$toJSON()
      }
      if (!is.null(self$`data_sources`)) {
        CompanyObject[['data_sources']] <- self$`data_sources`
      }

      CompanyObject
    },
    fromJSON = function(CompanyJson) {
      CompanyObject <- jsonlite::fromJSON(CompanyJson)
      if (!is.null(CompanyObject$`company_name`)) {
        self$`company_name` <- CompanyObject$`company_name`
      }
      if (!is.null(CompanyObject$`altana_canon_id`)) {
        self$`altana_canon_id` <- CompanyObject$`altana_canon_id`
      }
      if (!is.null(CompanyObject$`restrictions`)) {
        self$`restrictions` <- lapply(CompanyObject$`restrictions`, function(x) {
          restrictionsObject <- Restriction$new()
          restrictionsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          restrictionsObject
        })
      }
      if (!is.null(CompanyObject$`risks`)) {
        self$`risks` <- lapply(CompanyObject$`risks`, function(x) {
          risksObject <- Risk$new()
          risksObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          risksObject
        })
      }
      if (!is.null(CompanyObject$`company_context`)) {
        company_contextObject <- CompanyContext$new()
        company_contextObject$fromJSON(jsonlite::toJSON(CompanyObject$company_context, auto_unbox = TRUE))
        self$`company_context` <- company_contextObject
      }
      if (!is.null(CompanyObject$`data_sources`)) {
        self$`data_sources` <- CompanyObject$`data_sources`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "company_name": %s,
           "altana_canon_id": %s,
           "restrictions": [%s],
           "risks": [%s],
           "company_context": %s,
           "data_sources": [%s]
        }',
        self$`company_name`,
        self$`altana_canon_id`,
        lapply(self$`restrictions`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`risks`, function(x) paste(x$toJSON(), sep=",")),
        self$`company_context`$toJSON(),
        lapply(self$`data_sources`, function(x) paste(paste0('"', x, '"'), sep=","))
      )
    },
    fromJSONString = function(CompanyJson) {
      CompanyObject <- jsonlite::fromJSON(CompanyJson)
      self$`company_name` <- CompanyObject$`company_name`
      self$`altana_canon_id` <- CompanyObject$`altana_canon_id`
      self$`restrictions` <- lapply(CompanyObject$`restrictions`, function(x) Restriction$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`risks` <- lapply(CompanyObject$`risks`, function(x) Risk$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      CompanyContextObject <- CompanyContext$new()
      self$`company_context` <- CompanyContextObject$fromJSON(jsonlite::toJSON(CompanyObject$company_context, auto_unbox = TRUE))
      self$`data_sources` <- CompanyObject$`data_sources`
    }
  )
)
