# Altana Atlas API
#
# Altana Atlas for Regulatory Risk and Trade Compliance
#
# OpenAPI spec version: {{ version or \"v0.0.1\" }}
# Contact: engineering@altanatech.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' Edge Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Edge <- R6::R6Class(
  'Edge',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      EdgeObject <- list()

      EdgeObject
    },
    fromJSON = function(EdgeJson) {
      EdgeObject <- jsonlite::fromJSON(EdgeJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(EdgeJson) {
      EdgeObject <- jsonlite::fromJSON(EdgeJson)
    }
  )
)
