# Altana Atlas API
#
# Altana Atlas for Regulatory Risk and Trade Compliance
#
# OpenAPI spec version: {{ version or \"v0.0.1\" }}
# Contact: engineering@altanatech.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' Facilities Class
#'
#' @field num_results 
#' @field page_size 
#' @field page_num 
#' @field facilities 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Facilities <- R6::R6Class(
  'Facilities',
  public = list(
    `num_results` = NULL,
    `page_size` = NULL,
    `page_num` = NULL,
    `facilities` = NULL,
    initialize = function(`num_results`, `page_size`, `page_num`, `facilities`){
      if (!missing(`num_results`)) {
        stopifnot(is.numeric(`num_results`), length(`num_results`) == 1)
        self$`num_results` <- `num_results`
      }
      if (!missing(`page_size`)) {
        stopifnot(is.numeric(`page_size`), length(`page_size`) == 1)
        self$`page_size` <- `page_size`
      }
      if (!missing(`page_num`)) {
        stopifnot(is.numeric(`page_num`), length(`page_num`) == 1)
        self$`page_num` <- `page_num`
      }
      if (!missing(`facilities`)) {
        stopifnot(is.list(`facilities`), length(`facilities`) != 0)
        lapply(`facilities`, function(x) stopifnot(R6::is.R6(x)))
        self$`facilities` <- `facilities`
      }
    },
    toJSON = function() {
      FacilitiesObject <- list()
      if (!is.null(self$`num_results`)) {
        FacilitiesObject[['num_results']] <- self$`num_results`
      }
      if (!is.null(self$`page_size`)) {
        FacilitiesObject[['page_size']] <- self$`page_size`
      }
      if (!is.null(self$`page_num`)) {
        FacilitiesObject[['page_num']] <- self$`page_num`
      }
      if (!is.null(self$`facilities`)) {
        FacilitiesObject[['facilities']] <- lapply(self$`facilities`, function(x) x$toJSON())
      }

      FacilitiesObject
    },
    fromJSON = function(FacilitiesJson) {
      FacilitiesObject <- jsonlite::fromJSON(FacilitiesJson)
      if (!is.null(FacilitiesObject$`num_results`)) {
        self$`num_results` <- FacilitiesObject$`num_results`
      }
      if (!is.null(FacilitiesObject$`page_size`)) {
        self$`page_size` <- FacilitiesObject$`page_size`
      }
      if (!is.null(FacilitiesObject$`page_num`)) {
        self$`page_num` <- FacilitiesObject$`page_num`
      }
      if (!is.null(FacilitiesObject$`facilities`)) {
        self$`facilities` <- lapply(FacilitiesObject$`facilities`, function(x) {
          facilitiesObject <- Facility$new()
          facilitiesObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          facilitiesObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "num_results": %d,
           "page_size": %d,
           "page_num": %d,
           "facilities": [%s]
        }',
        self$`num_results`,
        self$`page_size`,
        self$`page_num`,
        lapply(self$`facilities`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(FacilitiesJson) {
      FacilitiesObject <- jsonlite::fromJSON(FacilitiesJson)
      self$`num_results` <- FacilitiesObject$`num_results`
      self$`page_size` <- FacilitiesObject$`page_size`
      self$`page_num` <- FacilitiesObject$`page_num`
      self$`facilities` <- lapply(FacilitiesObject$`facilities`, function(x) Facility$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
