# Altana Atlas API
#
# Altana Atlas for Regulatory Risk and Trade Compliance
#
# OpenAPI spec version: {{ version or \"v0.0.1\" }}
# Contact: engineering@altanatech.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' HSMisclassificationRisk Class
#'
#' @field risk_type 
#' @field risk_score 
#' @field predicted 
#' @field is_declared_hs2_equal_top_1 
#' @field is_declared_hs4_equal_top_1 
#' @field is_declared_hs6_equal_top_1 
#' @field is_declared_hs_equal_top_1 
#' @field is_declared_hs_in_top_3 
#' @field is_declared_hs_in_top_5 
#' @field is_tariff_diff_btw_declared_and_top_1 
#' @field top_predicted_confidence 
#' @field mean_predicted_confidence 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
HSMisclassificationRisk <- R6::R6Class(
  'HSMisclassificationRisk',
  public = list(
    `risk_type` = NULL,
    `risk_score` = NULL,
    `predicted` = NULL,
    `is_declared_hs2_equal_top_1` = NULL,
    `is_declared_hs4_equal_top_1` = NULL,
    `is_declared_hs6_equal_top_1` = NULL,
    `is_declared_hs_equal_top_1` = NULL,
    `is_declared_hs_in_top_3` = NULL,
    `is_declared_hs_in_top_5` = NULL,
    `is_tariff_diff_btw_declared_and_top_1` = NULL,
    `top_predicted_confidence` = NULL,
    `mean_predicted_confidence` = NULL,
    initialize = function(`risk_type`, `risk_score`, `predicted`, `is_declared_hs2_equal_top_1`, `is_declared_hs4_equal_top_1`, `is_declared_hs6_equal_top_1`, `is_declared_hs_equal_top_1`, `is_declared_hs_in_top_3`, `is_declared_hs_in_top_5`, `is_tariff_diff_btw_declared_and_top_1`, `top_predicted_confidence`, `mean_predicted_confidence`){
      if (!missing(`risk_type`)) {
        stopifnot(is.character(`risk_type`), length(`risk_type`) == 1)
        self$`risk_type` <- `risk_type`
      }
      if (!missing(`risk_score`)) {
        stopifnot(is.numeric(`risk_score`), length(`risk_score`) == 1)
        stopifnot(R6::is.R6(`risk_score`))
        self$`risk_score` <- `risk_score`
      }
      if (!missing(`predicted`)) {
        stopifnot(is.list(`predicted`), length(`predicted`) != 0)
        lapply(`predicted`, function(x) stopifnot(R6::is.R6(x)))
        self$`predicted` <- `predicted`
      }
      if (!missing(`is_declared_hs2_equal_top_1`)) {
        self$`is_declared_hs2_equal_top_1` <- `is_declared_hs2_equal_top_1`
      }
      if (!missing(`is_declared_hs4_equal_top_1`)) {
        self$`is_declared_hs4_equal_top_1` <- `is_declared_hs4_equal_top_1`
      }
      if (!missing(`is_declared_hs6_equal_top_1`)) {
        self$`is_declared_hs6_equal_top_1` <- `is_declared_hs6_equal_top_1`
      }
      if (!missing(`is_declared_hs_equal_top_1`)) {
        self$`is_declared_hs_equal_top_1` <- `is_declared_hs_equal_top_1`
      }
      if (!missing(`is_declared_hs_in_top_3`)) {
        self$`is_declared_hs_in_top_3` <- `is_declared_hs_in_top_3`
      }
      if (!missing(`is_declared_hs_in_top_5`)) {
        self$`is_declared_hs_in_top_5` <- `is_declared_hs_in_top_5`
      }
      if (!missing(`is_tariff_diff_btw_declared_and_top_1`)) {
        self$`is_tariff_diff_btw_declared_and_top_1` <- `is_tariff_diff_btw_declared_and_top_1`
      }
      if (!missing(`top_predicted_confidence`)) {
        stopifnot(is.numeric(`top_predicted_confidence`), length(`top_predicted_confidence`) == 1)
        stopifnot(R6::is.R6(`top_predicted_confidence`))
        self$`top_predicted_confidence` <- `top_predicted_confidence`
      }
      if (!missing(`mean_predicted_confidence`)) {
        stopifnot(is.numeric(`mean_predicted_confidence`), length(`mean_predicted_confidence`) == 1)
        stopifnot(R6::is.R6(`mean_predicted_confidence`))
        self$`mean_predicted_confidence` <- `mean_predicted_confidence`
      }
    },
    toJSON = function() {
      HSMisclassificationRiskObject <- list()
      if (!is.null(self$`risk_type`)) {
        HSMisclassificationRiskObject[['risk_type']] <- self$`risk_type`
      }
      if (!is.null(self$`risk_score`)) {
        HSMisclassificationRiskObject[['risk_score']] <- self$`risk_score`$toJSON()
      }
      if (!is.null(self$`predicted`)) {
        HSMisclassificationRiskObject[['predicted']] <- lapply(self$`predicted`, function(x) x$toJSON())
      }
      if (!is.null(self$`is_declared_hs2_equal_top_1`)) {
        HSMisclassificationRiskObject[['is_declared_hs2_equal_top_1']] <- self$`is_declared_hs2_equal_top_1`
      }
      if (!is.null(self$`is_declared_hs4_equal_top_1`)) {
        HSMisclassificationRiskObject[['is_declared_hs4_equal_top_1']] <- self$`is_declared_hs4_equal_top_1`
      }
      if (!is.null(self$`is_declared_hs6_equal_top_1`)) {
        HSMisclassificationRiskObject[['is_declared_hs6_equal_top_1']] <- self$`is_declared_hs6_equal_top_1`
      }
      if (!is.null(self$`is_declared_hs_equal_top_1`)) {
        HSMisclassificationRiskObject[['is_declared_hs_equal_top_1']] <- self$`is_declared_hs_equal_top_1`
      }
      if (!is.null(self$`is_declared_hs_in_top_3`)) {
        HSMisclassificationRiskObject[['is_declared_hs_in_top_3']] <- self$`is_declared_hs_in_top_3`
      }
      if (!is.null(self$`is_declared_hs_in_top_5`)) {
        HSMisclassificationRiskObject[['is_declared_hs_in_top_5']] <- self$`is_declared_hs_in_top_5`
      }
      if (!is.null(self$`is_tariff_diff_btw_declared_and_top_1`)) {
        HSMisclassificationRiskObject[['is_tariff_diff_btw_declared_and_top_1']] <- self$`is_tariff_diff_btw_declared_and_top_1`
      }
      if (!is.null(self$`top_predicted_confidence`)) {
        HSMisclassificationRiskObject[['top_predicted_confidence']] <- self$`top_predicted_confidence`$toJSON()
      }
      if (!is.null(self$`mean_predicted_confidence`)) {
        HSMisclassificationRiskObject[['mean_predicted_confidence']] <- self$`mean_predicted_confidence`$toJSON()
      }

      HSMisclassificationRiskObject
    },
    fromJSON = function(HSMisclassificationRiskJson) {
      HSMisclassificationRiskObject <- jsonlite::fromJSON(HSMisclassificationRiskJson)
      if (!is.null(HSMisclassificationRiskObject$`risk_type`)) {
        self$`risk_type` <- HSMisclassificationRiskObject$`risk_type`
      }
      if (!is.null(HSMisclassificationRiskObject$`risk_score`)) {
        risk_scoreObject <- BigDecimal$new()
        risk_scoreObject$fromJSON(jsonlite::toJSON(HSMisclassificationRiskObject$risk_score, auto_unbox = TRUE))
        self$`risk_score` <- risk_scoreObject
      }
      if (!is.null(HSMisclassificationRiskObject$`predicted`)) {
        self$`predicted` <- lapply(HSMisclassificationRiskObject$`predicted`, function(x) {
          predictedObject <- PredictedGoods$new()
          predictedObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          predictedObject
        })
      }
      if (!is.null(HSMisclassificationRiskObject$`is_declared_hs2_equal_top_1`)) {
        self$`is_declared_hs2_equal_top_1` <- HSMisclassificationRiskObject$`is_declared_hs2_equal_top_1`
      }
      if (!is.null(HSMisclassificationRiskObject$`is_declared_hs4_equal_top_1`)) {
        self$`is_declared_hs4_equal_top_1` <- HSMisclassificationRiskObject$`is_declared_hs4_equal_top_1`
      }
      if (!is.null(HSMisclassificationRiskObject$`is_declared_hs6_equal_top_1`)) {
        self$`is_declared_hs6_equal_top_1` <- HSMisclassificationRiskObject$`is_declared_hs6_equal_top_1`
      }
      if (!is.null(HSMisclassificationRiskObject$`is_declared_hs_equal_top_1`)) {
        self$`is_declared_hs_equal_top_1` <- HSMisclassificationRiskObject$`is_declared_hs_equal_top_1`
      }
      if (!is.null(HSMisclassificationRiskObject$`is_declared_hs_in_top_3`)) {
        self$`is_declared_hs_in_top_3` <- HSMisclassificationRiskObject$`is_declared_hs_in_top_3`
      }
      if (!is.null(HSMisclassificationRiskObject$`is_declared_hs_in_top_5`)) {
        self$`is_declared_hs_in_top_5` <- HSMisclassificationRiskObject$`is_declared_hs_in_top_5`
      }
      if (!is.null(HSMisclassificationRiskObject$`is_tariff_diff_btw_declared_and_top_1`)) {
        self$`is_tariff_diff_btw_declared_and_top_1` <- HSMisclassificationRiskObject$`is_tariff_diff_btw_declared_and_top_1`
      }
      if (!is.null(HSMisclassificationRiskObject$`top_predicted_confidence`)) {
        top_predicted_confidenceObject <- BigDecimal$new()
        top_predicted_confidenceObject$fromJSON(jsonlite::toJSON(HSMisclassificationRiskObject$top_predicted_confidence, auto_unbox = TRUE))
        self$`top_predicted_confidence` <- top_predicted_confidenceObject
      }
      if (!is.null(HSMisclassificationRiskObject$`mean_predicted_confidence`)) {
        mean_predicted_confidenceObject <- BigDecimal$new()
        mean_predicted_confidenceObject$fromJSON(jsonlite::toJSON(HSMisclassificationRiskObject$mean_predicted_confidence, auto_unbox = TRUE))
        self$`mean_predicted_confidence` <- mean_predicted_confidenceObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "risk_type": %s,
           "risk_score": %s,
           "predicted": [%s],
           "is_declared_hs2_equal_top_1": %s,
           "is_declared_hs4_equal_top_1": %s,
           "is_declared_hs6_equal_top_1": %s,
           "is_declared_hs_equal_top_1": %s,
           "is_declared_hs_in_top_3": %s,
           "is_declared_hs_in_top_5": %s,
           "is_tariff_diff_btw_declared_and_top_1": %s,
           "top_predicted_confidence": %s,
           "mean_predicted_confidence": %s
        }',
        self$`risk_type`,
        self$`risk_score`$toJSON(),
        lapply(self$`predicted`, function(x) paste(x$toJSON(), sep=",")),
        self$`is_declared_hs2_equal_top_1`,
        self$`is_declared_hs4_equal_top_1`,
        self$`is_declared_hs6_equal_top_1`,
        self$`is_declared_hs_equal_top_1`,
        self$`is_declared_hs_in_top_3`,
        self$`is_declared_hs_in_top_5`,
        self$`is_tariff_diff_btw_declared_and_top_1`,
        self$`top_predicted_confidence`$toJSON(),
        self$`mean_predicted_confidence`$toJSON()
      )
    },
    fromJSONString = function(HSMisclassificationRiskJson) {
      HSMisclassificationRiskObject <- jsonlite::fromJSON(HSMisclassificationRiskJson)
      self$`risk_type` <- HSMisclassificationRiskObject$`risk_type`
      BigDecimalObject <- BigDecimal$new()
      self$`risk_score` <- BigDecimalObject$fromJSON(jsonlite::toJSON(HSMisclassificationRiskObject$risk_score, auto_unbox = TRUE))
      self$`predicted` <- lapply(HSMisclassificationRiskObject$`predicted`, function(x) PredictedGoods$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`is_declared_hs2_equal_top_1` <- HSMisclassificationRiskObject$`is_declared_hs2_equal_top_1`
      self$`is_declared_hs4_equal_top_1` <- HSMisclassificationRiskObject$`is_declared_hs4_equal_top_1`
      self$`is_declared_hs6_equal_top_1` <- HSMisclassificationRiskObject$`is_declared_hs6_equal_top_1`
      self$`is_declared_hs_equal_top_1` <- HSMisclassificationRiskObject$`is_declared_hs_equal_top_1`
      self$`is_declared_hs_in_top_3` <- HSMisclassificationRiskObject$`is_declared_hs_in_top_3`
      self$`is_declared_hs_in_top_5` <- HSMisclassificationRiskObject$`is_declared_hs_in_top_5`
      self$`is_tariff_diff_btw_declared_and_top_1` <- HSMisclassificationRiskObject$`is_tariff_diff_btw_declared_and_top_1`
      BigDecimalObject <- BigDecimal$new()
      self$`top_predicted_confidence` <- BigDecimalObject$fromJSON(jsonlite::toJSON(HSMisclassificationRiskObject$top_predicted_confidence, auto_unbox = TRUE))
      BigDecimalObject <- BigDecimal$new()
      self$`mean_predicted_confidence` <- BigDecimalObject$fromJSON(jsonlite::toJSON(HSMisclassificationRiskObject$mean_predicted_confidence, auto_unbox = TRUE))
    }
  )
)
