# Altana Atlas API
#
# Altana Atlas for Regulatory Risk and Trade Compliance
#
# OpenAPI spec version: {{ version or \"v0.0.1\" }}
# Contact: engineering@altanatech.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' OneOfEdge Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
OneOfEdge <- R6::R6Class(
  'OneOfEdge',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      OneOfEdgeObject <- list()

      OneOfEdgeObject
    },
    fromJSON = function(OneOfEdgeJson) {
      OneOfEdgeObject <- jsonlite::fromJSON(OneOfEdgeJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(OneOfEdgeJson) {
      OneOfEdgeObject <- jsonlite::fromJSON(OneOfEdgeJson)
    }
  )
)
