# Altana Atlas API
#
# Altana Atlas for Regulatory Risk and Trade Compliance
#
# OpenAPI spec version: {{ version or \"v0.0.1\" }}
# Contact: engineering@altanatech.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' OneOfRisk Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
OneOfRisk <- R6::R6Class(
  'OneOfRisk',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      OneOfRiskObject <- list()

      OneOfRiskObject
    },
    fromJSON = function(OneOfRiskJson) {
      OneOfRiskObject <- jsonlite::fromJSON(OneOfRiskJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(OneOfRiskJson) {
      OneOfRiskObject <- jsonlite::fromJSON(OneOfRiskJson)
    }
  )
)
