# Altana Atlas API
#
# Altana Atlas for Regulatory Risk and Trade Compliance
#
# OpenAPI spec version: {{ version or \"v0.0.1\" }}
# Contact: engineering@altanatech.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' Risk Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Risk <- R6::R6Class(
  'Risk',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      RiskObject <- list()

      RiskObject
    },
    fromJSON = function(RiskJson) {
      RiskObject <- jsonlite::fromJSON(RiskJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(RiskJson) {
      RiskObject <- jsonlite::fromJSON(RiskJson)
    }
  )
)
