# Altana Atlas API
#
# Altana Atlas for Regulatory Risk and Trade Compliance
#
# OpenAPI spec version: {{ version or \"v0.0.1\" }}
# Contact: engineering@altanatech.com
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' TransactionRisk Class
#'
#' @field risks 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TransactionRisk <- R6::R6Class(
  'TransactionRisk',
  public = list(
    `risks` = NULL,
    initialize = function(`risks`){
      if (!missing(`risks`)) {
        stopifnot(is.list(`risks`), length(`risks`) != 0)
        lapply(`risks`, function(x) stopifnot(R6::is.R6(x)))
        self$`risks` <- `risks`
      }
    },
    toJSON = function() {
      TransactionRiskObject <- list()
      if (!is.null(self$`risks`)) {
        TransactionRiskObject[['risks']] <- lapply(self$`risks`, function(x) x$toJSON())
      }

      TransactionRiskObject
    },
    fromJSON = function(TransactionRiskJson) {
      TransactionRiskObject <- jsonlite::fromJSON(TransactionRiskJson)
      if (!is.null(TransactionRiskObject$`risks`)) {
        self$`risks` <- lapply(TransactionRiskObject$`risks`, function(x) {
          risksObject <- Risk$new()
          risksObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          risksObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "risks": [%s]
        }',
        lapply(self$`risks`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(TransactionRiskJson) {
      TransactionRiskObject <- jsonlite::fromJSON(TransactionRiskJson)
      self$`risks` <- lapply(TransactionRiskObject$`risks`, function(x) Risk$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
